<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\Stateflows\Stateflows.csproj" />
      <ProjectReference Include="..\Stateflows.Extensions.MicrosoftAgentFramework.Common\Stateflows.Extensions.MicrosoftAgentFramework.Common.csproj" />
    </ItemGroup>

</Project>
