<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\Stateflows\Stateflows.csproj" />
      <ProjectReference Include="..\..\Extensions\Stateflows.Extensions.ClearScript\Stateflows.Extensions.ClearScript.csproj" />
      <ProjectReference Include="..\..\Extensions\Stateflows.Extensions.MicrosoftAgentFramework\Stateflows.Extensions.MicrosoftAgentFramework.csproj" />
      <ProjectReference Include="..\..\Extensions\Stateflows.Extensions.MinimalAPIs\Stateflows.Extensions.MinimalAPIs.csproj" />
      <ProjectReference Include="..\..\Extensions\Stateflows.Extensions.Scheduling\Stateflows.Extensions.Scheduling.csproj" />
      <ProjectReference Include="..\Stateflows.Examples.Common\Stateflows.Examples.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Agents.AI.Foundry" Version="1.19.0-preview.260822.1" />
      <PackageReference Include="Microsoft.Agents.AI.Workflows" Version="1.19.0" />
    </ItemGroup>

</Project>
