<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\Stateflows\Stateflows.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Orleans.Reminders" Version="10.0.1" />
      <PackageReference Include="Microsoft.Orleans.Sdk" Version="10.0.1" />
      <PackageReference Include="Microsoft.Orleans.Server" Version="10.0.1" />
    </ItemGroup>

</Project>
