// <auto-generated />
using System;
using Examples.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examples.Storage.Migrations
{
    [DbContext(typeof(StateflowsDbContext))]
    partial class StateflowsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stateflows.Storage.EntityFrameworkCore.EntityFrameworkCore.Entities.Context_v1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BehaviorClass")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("BehaviorId")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TriggerOnStartup")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TriggerTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BehaviorClass");

                    b.HasIndex("BehaviorId")
                        .IsUnique();

                    b.HasIndex("TriggerOnStartup");

                    b.HasIndex("TriggerTime");

                    b.ToTable("StateflowsContexts_v1");
                });
#pragma warning restore 612, 618
        }
    }
}
